version: 2
groups:
- update-types: ["minor", "patch"]
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  versioning-strategy: increase # Update package.json too
  open-pull-requests-limit: 10
