version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  versioning-strategy: increase # Update package.json too
  open-pull-requests-limit: 10
  groups:
    patterns:
     update-types: 
        - "patch"
        - "minor"
