
name: standard-ci

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  test:
    strategy:
      matrix:
        node: [12, 14, 16]
        os: [ubuntu-latest]
    name: Node v${{ matrix.node }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Test
      run: yarn mocha

    - name: Lint
      run: yarn lint

