apiVersion: v1
kind: Secret
metadata:
  name: mongo-express
data:
  db-server-url: "bW9uZ29kYi5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsCg==" # replace with you mongodb url
  db-server-port: "MjcwMTcK"
  db-admin-username: "cm9vdAo="
  db-admin-password: "bXlwYXNzd29yZAo="
